
import { GoogleGenAI, Type } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables");
  }
  return new GoogleGenAI({ apiKey });
};

// Helper to strip base64 prefix if present for API usage
const stripBase64Prefix = (base64: string): string => {
  return base64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
};

const getMimeType = (base64: string): string => {
  const match = base64.match(/^data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+).*,.*/);
  if (match && match.length > 1) {
    return match[1];
  }
  return 'image/png'; // default
};

/**
 * Analyze an image and return a list of detailed clothing descriptions.
 */
export const analyzeClothingImage = async (imageBase64: string): Promise<string[]> => {
  const client = getClient();
  const mimeType = getMimeType(imageBase64);
  const data = stripBase64Prefix(imageBase64);

  const response = await client.models.generateContent({
    model: 'gemini-2.5-flash-image', // Capable of multimodal analysis
    contents: {
      parts: [
        {
          text: `Analyze this image and identify all distinct clothing items visible (e.g., tops, pants, dresses, outerwear).
                 For EACH item found, write a highly detailed visual description suitable for an image generator (include material, texture, color, cut, neckline, sleeve length, style).
                 
                 Return a JSON object with a property "items" which is an array of strings. 
                 Example: { "items": ["A blue denim jacket with vintage wash...", "A white cotton t-shirt..."] }`
        },
        {
          inlineData: {
            mimeType,
            data
          }
        }
      ]
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          items: {
            type: Type.ARRAY,
            items: { type: Type.STRING }
          }
        }
      }
    }
  });

  const jsonText = response.text;
  if (!jsonText) return ["Unable to analyze image."];

  try {
    const parsed = JSON.parse(jsonText);
    if (parsed.items && Array.isArray(parsed.items)) {
      return parsed.items;
    }
    return [jsonText];
  } catch (e) {
    console.error("Failed to parse analysis JSON", e);
    return [jsonText]; // Fallback
  }
};

/**
 * Generate clothing based on text description using NanoBanan (gemini-2.5-flash-image)
 */
export const generateClothingFromText = async (prompt: string): Promise<string> => {
  const client = getClient();
  
  const response = await client.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          text: `Generate a high-quality professional product photography image of the following clothing item:
                 "${prompt}".
                 
                 Requirements:
                 1. Layout: Ghost mannequin or flat lay style.
                 2. Background: Pure solid white background (#FFFFFF).
                 3. Focus: Show the entire garment clearly.
                 4. Quality: Photorealistic, high texture detail, 4k resolution.`
        }
      ]
    },
    config: {
        imageConfig: { aspectRatio: "1:1" }
    }
  });

  // Extract image from response
  if (response.candidates && response.candidates[0].content.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
  }

  throw new Error("No image generated by the model.");
};

/**
 * Generate the Try-On result using Multi-modal capabilities
 */
export const generateTryOnResult = async (
  modelImageBase64: string,
  clothingImageBase64: string,
  pose: string,
  angle: string
): Promise<string> => {
  const client = getClient();

  const modelMime = getMimeType(modelImageBase64);
  const clothingMime = getMimeType(clothingImageBase64);

  const modelData = stripBase64Prefix(modelImageBase64);
  const clothingData = stripBase64Prefix(clothingImageBase64);

  const response = await client.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
            text: `你是一位专业的虚拟试衣设计师。
            图片1: "模特" (Model)。
            图片2: "服装单品" (Clothing Item)。
            
            任务: 生成一张【模特】穿着【服装单品】的真实照片。
            
            要求:
            1. **合成**: 将图片2的服装完美贴合在图片1的模特身上。
            2. **一致性**: 保持模特的脸、发型、体型不变。
            3. **姿态与视角**: 
               - 动作: ${pose}
               - 视角: ${angle}
            4. **真实感**: 处理好衣物褶皱、光影和透视关系。背景保持简约。`
        },
        {
          inlineData: {
            mimeType: modelMime,
            data: modelData
          }
        },
        {
          inlineData: {
            mimeType: clothingMime,
            data: clothingData
          }
        }
      ]
    },
    config: {
        imageConfig: {
            aspectRatio: "3:4"
        }
    }
  });

   if (response.candidates && response.candidates[0].content.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
  }

  throw new Error("Failed to generate try-on result.");
};
